### ISSUE TITLE
AdminUI, at the SIP numbers list need to show the RVD project names.

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Connect#1000]
You need to be able to know from the list of the SIP number which project is associated with with RVD app. At the moment you see only the encoded name of the project which is not useful. 

![numberrvd](https://cloud.githubusercontent.com/assets/4802924/14556263/fa711be8-02ff-11e6-8452-8d794f86be04.png)

**Comment by otsakir** [comment]
Indeed, showing the project IDs does not help much. Also, to be precise, it's not the *RVD project name* any more but the *Application Friendly Name* which is currently stored in Applications table. 

I can't figure out an elegant way to display it. The problem is that AdminUI asks for a DID list. Not an application list. The application name is not part of the DID entity. 

Some thoughts:

1. Add a method to Applications endpoint to return a set of applications for a specified set of applications SIDs. We query that method passing all applications SIDs for shown DIDs
2. Add the application name in the produced DID entity returned by Restcomm.

@gvagenas , @ghjansen wdyt  guys ?

**Comment by ghjansen** [comment]
Yes, i remember that at that time this was a fast solution because get the name of each Application require something else. I think i would with 1 rather than 2. 
Plus, we already have a list of Applications that is loaded on AngularJS by opening some detail pages. Maybe we could adapt this part and use it.

**Comment by deruelle** [comment]
I vote for 1. too

**Comment by gvagenas** [comment]
@otsakir I believe the best option is to go for 2. This will reduce the unnecessary complexity at Admin UI side.
You can add a new property for DID entity , applicationName, that will contain the Application Name (in the case of DID configured with Application SID) or the URL (in the case DID configured with plain URL). 
The IncomingPhoneNumber API that will provide the list of DIDs can query and get the Application Name. 
This solution is more clean to me

**Comment by gvagenas** [comment]
Closed with PR https://github.com/RestComm/Restcomm-Connect/pull/1241
