### ISSUE TITLE
When RC is under LB rejects the call for registration to different instance.

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Connect#1262]
When RC is under LB controls the WebRTC client registration, and reject the call if user is register to different RC instance.

Logs:
08:22:11,244 WARN  [org.mobicents.servlet.restcomm.telephony.CallManager] (RestComm-akka.actor.default-dispatcher-2132) Cannot create call for user agent: sip:alice@*.*.*.*:40704;transport=wss since this is a webrtc client registered in another Restcomm instance.

 08:22:11,244 ERROR [org.mobicents.servlet.restcomm.telephony.CallManager] (RestComm-akka.actor.default-dispatcher-2132) The SIP Client alice is not registered or does not exist

**Comment by leftyb** [comment]
From RC side, can look for the LB header and disable/enable  this functionality: 
From the REGISTER message :

08:34:55,139 DEBUG [gov.nist.javax.sip.stack.ConnectionOrientedMessageChannel] (pool-AffinityJAIN-thread-43) hop port = 5083 for request REGISTER sip:staging.restcomm.com SIP/2.0
Call-ID: 1467880495058
CSeq: 1 REGISTER
From: <sip:alice@staging.restcomm.com>;tag=1467880495059
To: <sip:alice@staging.restcomm.com>
Via: SIP/2.0/WSS IP:5083;branch=z9hG4bK-323633-257e00948092fbe3ba7ccf0f5623d77c14678zsd_0
Via: SIP/2.0/WSS IP:5063;branch=z9hG4bK-323633-257e00948092fbe3ba7ccf0f5623d77c14678_0
Via: SIP/2.0/WSS IP:40727;branch=z9hG4bK-323633-257e00948092fbe3ba7ccf0f5623d77c;rport=40727;received=IP
Max-Forwards: 69
User-Agent: TelScale RTM Olympus/1.0.0
Expires: 3600
Allow: INVITE,ACK,CANCEL,BYE,OPTIONS,MESSAGE
Contact: <sip:alice@IP:40727;transport=wss>
X-Sip-Balancer-InitialRemoteAddr: IP
X-Sip-Balancer-InitialRemotePort: 40727
Route: <sip:RC_IP:5083;transport=wss;lr>
Content-Length: 0

**Comment by gvagenas** [comment]
@leftyb When WebRTC clients registers with LB there will be one websocket connection, Client - WebSocket. 
Next, LB will pick one of the available Restcomm nodes, will create websocket connection and will dispatch the REGISTER message for the client to register.
Finally there will be 2 websocket connections, Client to LB and LB to Restcomm_Node_X.

For Restcomm (or any other sip entity) to dial a WebRTC client. needs to have access to the websocket connection.

So that means that even if we provide a patch to not check if the WebRTC client is behind LB, Restcomm will not be able to dial this client if it doesn't belong the websocket connection.

I close this issue since the instance Id check for calling WebRTC clients is ok and we cannot remove or modify.

We need to check for another workaround for how to dial WebRTC clients.
