### ISSUE TITLE
Delete an account doesn't work

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#1270]
http://documentation.telestax.com/connect/api/account-api.html#delete-sub-accounts

`curl -X DELETE https://[primarysid]:|PWD]@cloud.restcomm.com/restcomm/2012-04-24/Accounts/AC3b8f0dd2e5026abde018446cbb3b185d.json` returns
=> The specified HTTP method is not allowed for the requested resource 

Also Admin UI doesn't allow to delete a sub account 

![screenshot from 2016-07-08 23 14 17](https://cloud.githubusercontent.com/assets/54279/16701735/f5b0724e-4561-11e6-896a-8fa68f11531d.png)

**Comment by gvagenas** [comment]
@deruelle To use the JSON endpoint you need to use "Accounts.json" in the url. Will update docs and there is already an issue for the REST API inconsistency https://github.com/RestComm/Restcomm-Connect/issues/898

**Comment by deruelle** [comment]
@gvagenas so curl -X DELETE https://[primarysid]:|PWD]@cloud.restcomm.com/restcomm/2012-04-24/Accounts.json/AC3b8f0dd2e5026abde018446cbb3b185d or curl -X DELETE https://[primarysid]:|PWD]@cloud.restcomm.com/restcomm/2012-04-24/Accounts.json?AC3b8f0dd2e5026abde018446cbb3b185d or something else ?

**Comment by gvagenas** [comment]
@deruelle This one:
curl -X DELETE https://[primarysid]:|PWD]@cloud.restcomm.com/restcomm/2012-04-24/Accounts.json/AC3b8f0dd2e5026abde018446cbb3b185d.json

**Comment by deruelle** [comment]
@gvagenas  Thanks that worked.

@otsakir @brainslog can you look at Admin UI and see why the Delete Account Button doesn't work ?

**Comment by muhammadbilal19** [comment]
@deruelle just by looking into the UI page i can see this button is doing nothing there is no action attached with this button. So we need to write a new JS function for delete account call and attached it with this delete button.

**Comment by deruelle** [comment]
@muhammadbilal19 would you like to contribute that ?

**Comment by otsakir** [comment]
Before enabling the button, i've just noticed that removing an account doesn't seem to go in much depth. Only the account entity is removed as well as the account's clients. What about Numbers, Applications etc ? Shouldn't these be removed too as well as the remaining entities that are related to this account ? 

There is also the solution of marking the account as 'deleted' and keeping it there (i'm not suggesting, just putting it on the table here).

thoughts ?

**Comment by deruelle** [comment]
@otsakir The suspend feature is already present but you're right I think everything tied to the account should be deleted as well as described in https://www.twilio.com/help/faq/twilio-basics/how-do-i-close-a-subaccount

**Comment by kkampardi** [comment]
@deruelle , right. However, twilio seems to keep the actual account record (in CLOSED state) but delete all the related entities. I'm wondering whether this makes some sense instead of removing it altogether.

**Comment by otsakir** [comment]
@deruelle , right. However, twilio seems to keep the actual account record (in CLOSED state) but delete all the related entities. I'm wondering whether this makes some sense instead of removing it altogether.

**Comment by deruelle** [comment]
@otsakir it does make sense so that we can track previous activity on an account in case of fraud, issues, etc

**Comment by otsakir** [comment]
Team, i've done some reasearch regarding account removal and things we need to consider before proceeding. Note, my knowledge on restcomm internals is not complete. Please have a look and provide feedback.

The following entities are connected to an Account (i.e. have an accountSid as a foreign key). Some of these entities will be removed and some should linger. I've tried to visualize their removal and foresee if everything will be ok. Here are the results:

* Sub-accounts and sub-accounts resources

  The idea is to move them in a final CLOSED state. I suggest we do the same their sub-accounts. Also, whatever policy we follow for the parent account seems appropriate for sub-account too.

* Announcements - no issues
* Applications

  Application themselves can be removed easily. But what happens with the respective RVD project ? There is no behavior define for that yet. Just removing the application using the API will result in orphaned (with no application pointing to it) project in RVD. Currently, such projects exist in filesystem but do not appear in RVD listing. Also, since the account is disabled/removed it won't be possible to login to RVD as this account anymore. So, we will end up with garbage. I can think of the following solutions:
  1. Setup RVD to run periodic checks and remove such projects. Meanwhile, we make sure the projects are not executable.
  2. Notify RVD to handle the removal. 
  
     Currently there is no proper RVD api for that. The existing project removal method will also reach back to restcomm to remove the respective Application record. The reason is that as we speak these operations were controlled by RVD. The trend however is to move this kind of control to restcomm. For example remove apps/projects from AdminUI. Here is a related issue:
     
     https://github.com/RestComm/Restcomm-Connect/issues/946
     
     In that sense, any Restcomm compatible application server will have to implement an HTTP API to receive notifications about restcomm events that are of interest to it. Like an 'OnApplicationRemoved' event for example.

* CallDetailRecords

  Foreign keys:
    - parentCallSid
    - conferenceSid
    - phoneNumberSid
    
  Shall we keep or remove CDRs? If i recall corrently a discussion with George, we keep them. If we decide to remove them though here are some considerations:
  - What happens with parent/child call detail records. Do they belong to the same account by definition ? If not is it ok to remove only one of them ? @gvagenas ?
  - The relation to phoneNumberSid seems innocent. No issues for phoneNumbers with no CDRs are apparent.
  - What about conferenceSid ? @maria-farooq ?
    
* Clients

  Foreign keys:
  - voiceApplicationSid foreign 
  
  It doesn't seem like a has-a relationship. We could just remove them. Possible runtime issues with Clients currently registered or having calls. @gvagenas ?
  
* ConferenceDetailRecords

  Is there any reason to keep these ? 
  
  @maria-farooq ?
  
* IncomingPhoneNumbers  

  Foreign keys:
  - voiceApplicationSid
  - smsApplicationSid
  
  I can see no issues with the foreign keys. If we decide to keep the CDRs that point to these numbers, we could face CDRs with missing numbers though. That seems ok since it's a situation that is already on the table. @george ?
    
* Notifications

  Foreign keys:
  - callSid
  
  It seems we can safely remove them.

* OutgoingCallerIds

  No problem here either.
  
* Recordings

  Foreign keys:  
  - callSid
  
  It seems that we can safely remove them. They are related to Transcriptions (from the other side) so, i guess, we should apply the same policy to both.
  
* Short codes - no issues
  
* SmsMessages

  Any billing implications ? Maybe we need to keep references to SmsMessages for future billing evidence. @deruelle , @gvagenas ?
  
* Transcription

  Foreign keys:
  - recordingSid
  
  It seems we can remove these. Apply the same policy as with the Recordings.
  
* Usage

  No removal operation in Dao. Also, we probably need to keep this for billing purposes.

##### In-Memory entities

The following entities have references to AccountSid but since there is no DAO for them i suppose they are kept in memory:

 - IncomingPhoneNumberFilter
 - ConferenceDetailRecordFilter

Are there any runtime integrity issues introduced if we disable the accounts they belong to ? I guess not. What if we remove them ? @deruelle , @maria-farooq  ?

**Comment by gvagenas** [comment]
@otsakir All call detail records should be kept to my opinion, CDRs and ConferenceDetailRecords and SmsMessages should be kept

IncomingPhoneNumbers should be removed and released from the provider, e.g. Nexmo.

Clients can be removed also, even if there is a ongoing call since the account needs to be removed then the clients are not valid anymore.

For Application and RVD projects, I believe we should go for your first approach for RVD to periodically check and remove orphan projects. It wouldn't be good to put some new dependencies on the external application servers.

Notifications we should keep them I think

Sub-accounts should be moved to closed also.

I think if we cover these issue we will be fine

George

**Comment by maria-farooq** [comment]
@otsakir i agree with @gvagenas 's answer to keep the records (same goes for conferenceDetailRecord)
for ConferenceDetailRecordFilter: this entity is used to create various `where` clause queries to select data from ConferenceDetailRecord. 
So even if account is deleted, we will be ok.
can you please explain last part of your last question. in context of (ConferenceDetailRecordFilter)
> what if we remove them?

**Comment by otsakir** [comment]
Thanks for the feedback.

@maria-farooq,  you have covered the question. 
> So even if account is deleted, we will be ok.

@gvagenas, ok about Applications and RVD. We can move on with solution 1 and either handle this with either with periodic checks or on RVD-UI level when the discrepancies are detected and are about to be shown.

Note my disagreement on this however. I believe it saves some complexity on the core restcomm side but introduces more to the whole system.

**Comment by deruelle** [comment]
@gvagenas @otsakir on Applications and RVD, @otsakir what you are proposing is to be able to configure callback URLs for when some actions are performed on Restcomm Core itself ? 
By example, if an application is removed then a HTTP POST is done to a callback URL (in this case RVD) so the external application (RVD) depending on that can take proper action ? 

If that's the approach envisioned, we should go for it, it's much cleaner and less error prone and consistent with the REST of the Restcomm API design which defines callbacks on some Verbs when an action is completed.

**Comment by otsakir** [comment]
@deruelle, right, that's my suggestion. It seems cleaner overall to me and is also a common notification pattern already used by restcomm.

**Comment by deruelle** [comment]
@otsakir I think those HTTP calls should be asynchronous to avoid having the API (or Admin UI) hanging. One question though is if the external application is not available and the HTTP is timing out, how would the external application handles that when recovering ?

**Comment by otsakir** [comment]
@deruelle, valid point about 
> having the API (or Admin UI) hanging

Regarding AdminUI i don't think there will be a problem as the whole thing works in an asynchronous way by default. So, When pressing 'Delete account' the request is sent and a spinning icon can be displayed on the button. The user does not have to wait until this completes but can continue using the application. Upon completion a 'success' notification appears. The same should apply in all operations that are triggered through AdminUI though we 're not really using this. The important thing here is that the account removal itself is NOT atomic but is done in steps that leave the system in a consistent state. So, we should first remove dependency entities (e.g. DIDs) and then the dependent ones (e.g. account).

For the API, things seem tougher. The thread that will serve the request might take too long to respond. There are a lot of DB and network operations to be done. Contacting external entities (like RVD) can be a bottleneck. We could rely on timeouts for the external notification requests but it could take long if several projects are involved.

On the other hand removing accounts with lots of deps won't be common and is expected to take some time. The implementation could abandon the notifications to the application server once a timeout has been crossed or a serious error is returned. 

Regarding
> One question though is if the external application is not available and the HTTP is timing out, how would the external application handles that when recovering ?

I believe a fallback mechanism from the side of RVD should exist. Like a maintenance task when the projects are listed, a lazy mechanism that will remove projects once they are detected or an indication to the user (since the owner account is removed it could be done by the administrator - note, administrator can not access the projects if the child accounts yet but it's a feature we need to implement) that some projects are orphaned so that he takes action himself.

In any case, there will a removal mechanism for orphaned projects from the RVD side that won't rely on notifications. I will proceed to building it now, to have 1270 solved. We can continue the discussion on notifications to cover all shortcoming and see if it fits our purpose.

**Comment by deruelle** [comment]
> For the API, things seem tougher. The thread that will serve the request might take too long to respond. There are a lot of DB and network operations to be done. Contacting external entities (like RVD) can be a bottleneck. We could rely on timeouts for the external notification requests but it could take long if several projects are involved.
> 
> On the other hand removing accounts with lots of deps won't be common and is expected to take some time. The implementation could abandon the notifications to the application server once a timeout has been crossed or a serious error is returned.

Shall we assume an async call as well for those notifications meaning it's only a notification and not part of the whole deletion system so the REST API doesn't depend on the answer to the notification from the external application to ensure consistency. It basically just notify async and we avoid that way requests that takes too long. Especially if we need to have a fallback mechanism anyway on the external application side.

**Comment by otsakir** [comment]
Yes, definitely. It's best-effort.

**Comment by otsakir** [comment]
@gvagenas  @deruelle 

I'm facing the following dilemma regarding what means "removing an account". Current  implementation removes the account record (and children) altogether. It does not put it in CLOSED state. 

If we switch to *leaving the account record be but setting the state to 'CLOSED'* what happens with future records that have the same email address? And also, is this a realistic case we have to worry about ?

There is also issue https://github.com/RestComm/Restcomm-Connect/issues/1295 that complicates things as it enforces emailAddress field uniqueness. So, practically we can't keep many account with same email address.

**Comment by deruelle** [comment]
@gvagenas @otsakir I'm not sure I understand why  #1295 is complicating things. Shouldn't it simplify things as the whole goal is to make the AccountSid independent of the email address. If #1295 is fixed, then if someone opens a new account with same email address they will get a new AccountSid that won't be tied to the email address. if a lookup needs then to be done on the email address, only the current account with OPEN  state should be returned. If there is no account with OPEN State then an aggregation of records from all accounts in CLOSED state with that email ?

**Comment by otsakir** [comment]
@deruelle, you're right. I agree. what i meant by
> complicates things 

is that we need to first take care of #1295 if we want to support "CLOSing" accounts instead of removing them. I'll post further comments regarding email-address uniqueness  there. I remember there were some shortcomings after a discussion with @gvagenas.

**Comment by gvagenas** [comment]
@otsakir @deruelle I provided my comments to #1295 and there is a reason we have accountSid generated by email address.

To my opinion we should have accounts to CLOSED state and check to re-enable if needed later

**Comment by gvagenas** [comment]
@otsakir @deruelle As we discussed on the phone with Orestis, my opinion is that the most flexible way to handle this is the following:
1. Delete an account default action should be to move the account to CLOSED state, and also release some of the resources, for example DIDs, and keep others, for example CDRs. Also we should provide an extra parameter to completely remove the account from the DB as this will be needed in some cases, but this wont be the default action.
2. Re-enable the account should not mean, create a new one, new account sid same email address, but instead should mean move the existing account from CLOSED to ACTIVE state. This way you can see your existing CDRs etc. 
3. I agree and I see no problem to break the link between account SID and email address (#1295) and so the account sid is completely random, but I believe that if someone tries to create a new account using existing email address, Restcomm should check if there is an account with that email address re-enable the account (move the state to ACTIVE) instead of create a new one.

George

**Comment by deruelle** [comment]
@gvagenas @otsakir That makes sense.

One caveat though is that removing completely an account from the DB may be problematic. We may need to forbid that for legal and security reasons, some countries will require that all activity is tracked for security reasons. Otherwise one could open an account, spam, delete the account forever without being tracked. Same thing for fraud.

We could potentially ask the user when creating the account that an account for that email address already exists but has been closed and whether or not it should be reopened or if a new should be created in which case Restcomm should check if there is an account with that email address re-enable the account (move the state to ACTIVE) only if the user agrees to it otherwise create a new one with the rule that only one account tied to an email address can be in ACTIVE state at any given point in time.

thoughts ?

**Comment by otsakir** [comment]
@deruelle , @gvagenas , I believe both of these stand:

a. In cloud environments email addresses are unique and through time owned by the same physical entity. It seems appropriate to allow closing and re-opening accounts under conditions. Facebook keeps account for sure and google also i suppose. The account is an asset that once created stays for a long time.
b. There can be cases when an account should be wiped out. For example for non-cloud installations where the email address is not really used as an address but only works as an identifier/username. Also, in cloud environments some accounts may be created accidentally or for testing purposes. For such cases there should be actual removal from the DB. 

Here are some suggestions/assumptions that will help me proceed with the implementation. Please provide feedback and corrections:

1. Typical account closing should be the action that happens when a user presses "Delete account" in AdminUI. The owner user as well as his parent accounts can do this. Under the hood this will be implemented as an update account request with Status=CLOSED. Once the account is closed it will be sealed. No more updates allowed.

2. Top-level account (Super admin) will also be able to do a "Wipe/purge account" in AdminUI. That will be implemented as a DELETE request that will totally remove an account.

3. Closed accounts credentials cannot be used for login. Authentication fails for such accounts. 

4. Parents of closed accounts can query them just as if they are normal accounts. Status is set to CLOSED. Does it make sense to display them or hide them in adminUI ?

5. Parent accounts can query closed account resources. For example a parent can ask for CDRs of his closed child (i'm not referring to the newly created subAccount=true flag but to ask directly for the child's calls e.g. /ACxxxChildSidxxx/Calls.json). 

6. Trying to create a new account with an email address that's already taken by closed account will result in an "email address already taken" message in AdminUI.

7. Define re-opening policy. Who can re-open an account? Is it the owner user? Is it its parent account ? Differences in cloud/standalone installations? Are there any ?

**Comment by deruelle** [comment]
@otsakir @gvagenas as discussed on gitter today.

> For 2. Top-level account (Super admin) will also be able to do a "Wipe/purge account" in AdminUI. That will be implemented as a DELETE request that will totally remove an account.

Let's allow that only to be done via a script externally as if super admin account gets hacked, it could remove and wipe all the accounts which is a too big security risk.

>  4. Does it make sense to display them or hide them in adminUI 

Yes under a filter. If closed account are enabled then we display them if not we don't, or we display all by default and display in the list if this is for a closed account or not with a priority on non closed accounts.

> 7.Define re-opening policy. Who can re-open an account? Is it the owner user? Is it its parent account ? Differences in cloud/standalone installations? Are there any ?

I think the account owner and parent account can reopen except if the account was marked as suspended. If the account is suspended only parent account can reopen I think.

**Comment by otsakir** [comment]
@gvagenas , @deruelle , regarding account removal synchronization with Application Server (RVD) i propose the following:

* Standardization of an (optional) application server REST API consumed by Restcomm. Application servers will implement this if they wish. Restcomm, if configured, will consume it. 
* The configuration in restcomm.xml will look like this:
```
<application-server-api>
    <base-url>/restcomm-rvd/services/</base-url>
    <notifications>true</notifications>
</application-server-api>
```
* RVD will contain a new resource under /restcomm-rvd/services/Notifications to handle notifications from Restcomm. For example:
```
POST /restcomm-rvd/services/Notifications
type=applicationRemoved&applicationSid=APxxxxxxxxxxxxxxx
```
* For authentication, Restcomm will supply the credentials of the application owner account. RVD will use them to reach back to Restcomm and authenticate. If it succeeds, and the project is owned by the same user it will proceed to removal.
* Restcomm will POST a notification for every application removed in an async way as described here roughly:
https://jersey.java.net/documentation/latest/async.html#d0e10548
* Responses will NOT be processed in an async way. The concept works in a best effort basis.

Please place your thoughts and doubts.

**Comment by deruelle** [comment]
@otsakir 

> Standardization of an (optional) application server REST API consumed by Restcomm. Application servers will implement this if they wish. Restcomm, if configured, will consume it.

This reads as if Restcomm-Connect will receive notifications from the application server while it is the other way around. Your description after that makes sense to me and I'm in agreement

**Comment by otsakir** [comment]
@deruelle , @gvagenas , regarding RVD notification mechanism, there are two points i need a second opinion:

1. Application removal in restcomm is done by a single query that removes all applications that have a specific accountSid property. I think it makes sense to have a notification event for account removal/closing too in addition to application removal. wdyt ?

2. What happens with authentication ? Example: top-level account administrator@company.com,  has a child account, orestis@company.com. The latter owns an application/project. Either administrator or orestis should be able to close the account and remove the application/project. 

Let's say that administrator@company.com closes orestis's account using AdminUI or the API directly:

- Restcomm makes a notification request to RVD when orestis' account is removed. Admin's credentials are forwarded to RVD too.
- Upon receiving the notification request RVD will first authenticate the credentials by reaching back to restcomm. 
- RVD loads the project that is being removed and gets its owner, i.e. orestis@company.com. It then tries to retrieve the orestis@company.com account using the credentials it received in the notification request i.e. administrator@company.com. 
- If it succeeds, it means that admistrator@company.com has read access to orestis@company.com. This is treated as equivalent to "is the-same or a-parent-of" orestis@company.com. RVD proceeds to removing all applications of orestis@company.com.

In this draft, being able to retrieve an account means being able to remove all projects of an account.

wdyt ?

**Comment by deruelle** [comment]
@otsakir 
1. Agreed
2. Agreed. We could also potentially pass the application owner's credentials right away instead of the parent one to avoid too many round trips and complexity + point of failures

**Comment by otsakir** [comment]
@deruelle , about (2), that was the initial plan. The problem here is that we have to assume that an account in any state other than CLOSED will always allow to be authenticated and return a 200OK in the case the credentials passed are correct. I'm wondering is this a safe assumption to do for accounts in UNINITIALIZED or SUSPENDED state?

Another thing that crossed my mind is that it may confuse auditing. We will have requests reaching back restcomm that will not carry the credentials of the user that actually triggered the account removal, but of the sub-account that is being removed.

wdyt?

**Comment by deruelle** [comment]
your second point makes a lot of sense. I agree with your approach

**Comment by otsakir** [comment]
Some thoughts on account retrieval return values and http statuses...

1. Trying to retrieve an account B that is closed using credentials of a parent account A that is still open and has read access to B will (a) return the account with status -> 'CLOSED' and (b) return http status 200 OK.
2. Trying to retrieve closed account B using credentials of any account that has not access to B should return 403.
3. Trying to retrieve closed account B using valid B's credentials should return 410 - Gone. no response body returned.
4. Trying to retrieve closed account B using invalid B's credentials should return 404 and not 403. That way one won't be able to tell that a closed account exists by using invalid credentials.

The following is about 410 - Gone:

https://tools.ietf.org/html/rfc7231#section-6.5.9

**Comment by deruelle** [comment]
@otsakir I would make both 2 and 4. return 404

**Comment by otsakir** [comment]
ok @deruelle, thanks for the feedback.

Regarding issues that are still open, i'm copying form the email thread:


Jean,

About (1), i haven't been able to setup aquilian to work with two web application, namely RVD and restcomm. Restcomm needs a SIP container to run. RVD can't run at the same time using the same or another instance of the sip container. There is no problem with typical tomcat containers, but with the mobicents version i couldn't make this work. As we speak, i don't remember the exact internal obstacles to describe them accurately, but all attempts i've made in the past to set this up using arquilian have failed. That leaves me with splitting the tests in half. Test restcomm and RVD in isolation using wiremock. The more http requests need to be wire-mocked the less the real value of the test.

Regarding (2), it's on the restcomm side. RVD doesn't care whether these calls are async or not. It will just proceed and should be able to handle the case that the account-to-be-removed may already me missing when RVD gets to remove its projects.

thoughts ?



On Fri, Oct 7, 2016 at 11:14 PM, Jean Deruelle wrote:

    Thanks Orestis.

    Why is 1) impossible ? Can you give more insights here ?
    2) new things needed in Restcomm or RVD ?

    On Fri, Oct 7, 2016 at 8:47 PM, Orestis Tsakiridis wrote:

        Adding my offline update...

        Orestis

        Investigated and fixed RVD startup issue #1460.
        Wrapping up issue #1270 on account removal. Notification mechanism is almost ready but there are two shortcommings. (1) Proper integration test including both retscomm RVD is seems impossible. (2) Async calls need a deeper look as a different type of connection manager seem to be needed as well as a reactor.

**Comment by deruelle** [comment]
On 1) Noted it's a current limitation of our testing setup with arquillian that will require an update from the SIP Servlets team at some point, maybe @gvagenas can help on trying to deploy 2 webApps at the same time.

2) I'm not sure I got it. I would say RVD when it removes its project from such a removal request from Admin UI. are you referring to this as new issue because of the decision taken in https://github.com/RestComm/Restcomm-Connect/issues/1270#issuecomment-251864969 ? If so we may need to revisit our options and pros and cons.

**Comment by otsakir** [comment]
@deruelle , regarding (2),  the notification request is sent from *restcomm* to RVD and not from *AdminUI* to RVD. Are we on the same page on that?

The status here is that i've finished my research and tests on async classes that will be used to notifify RVD and started the implementation. The idea roughly is that restcomm will first come down with the set of accountSids that are removed and then start a thread that will make all notifications using async client.

**Comment by deruelle** [comment]
@otsakir yeah I meant Restcomm sorry, not Admin UI

**Comment by otsakir** [comment]
According to current implementation closed accounts should allow authentication and also return their closed accound children if asked. 

Thus, suppose parent@company.com has a sub-account child@company.com. If parent@company.com is closed, restcomm should allow the following:
- retrieve parent@company.com using parent's credentials
- retrieve child@company.com using parent's credentials

@deruelle , @gvagenas , seeing any major flaws in this logic ?

Since we didn't have have the *closed accounts* notion so far, this behavior has not been put to practice. I'm taking advantage of it however to let RVD authenticate closed accounts asynchronously.

**Comment by gvagenas** [comment]
@otsakir I think we can allow authenticate only for the Account REST API and only for the update method (that will be used for close and re-open) but that can lead to security risks and maybe the re-open should be left to a higher account to avoid security risks.

**Comment by otsakir** [comment]
@gvagenas , you have a valid point. I can see the following alternatives:

1. Since the problem here is mainly authentication of notification requests, and since sending notifications is a sort of administrative task, we introduce a secret token that restcomm will use to authenticate to RVD. Thus, the restcomm.xml configuration becomes sth like this:

  ```
<application-server-api>
    <base-url>/restcomm-rvd/services/</base-url>
    <notifications>true</notifications>
    <secret-token>this-proves-i-am-restcomm</secret-token>
</application-server-api>
  ```

  The same will be present from the RVD side in rvd.xml:

  ```
  ...
  <administrative-token>this-proves-i-am-restcomm</administrative-token>
  ...
  ```

  There are some security concerns since we're storing passwords in configuration files. Things will be better in SSO.

2. Account closing will work synchronously when one closes his own account. So, the account that RVD will use for authentication will be present when RVD asks for it since restcomm will wait for RVD to finish. If one closes a sub-account (and not his own) the process will be asynchronous since the account that triggered the authentication will not get affected. 

  Obviously there is some complexity introduced in the implementation but i think it's possible.

3. Forget asynchronous implementation altogether.

**Comment by gvagenas** [comment]
@otsakir I believe synchronous will work since only one Jersey thread will block but I believe the best solution will be the following:
1. Restcomm sends request to RVD synchronously and blocks to wait for the response (only the jersey thread blocks)
2. RVD gets the request, authenticates the request, makes any checks it needs and 
  i. returns response so Restcomm doesn't block anymore
  II. starts removing files and projects

George

**Comment by otsakir** [comment]
Quoting @gvagenas  form slack thread:

1. All REST API should check account status and deny requests from CLOSED state accounts
2. For a user to close an account and since we need to notify RVD (that needs to authenticate the request) Restcomm should block waiting for RVD to authenticate the account (while account is still active) and then Restcomm to proceed to cleanup and change state to CLOSED. Restcomm/RVD could fully block untill all operations are done (synchronous) or Restcomm sends request to RVD and blocks, RVD 1)authenticates 2) does some preparation if needed 3) assigns the task to a new thread to make the clean up async 4) sends back response to Restcomm and thus Restcomm doesn’t block any more
3. To re-open or retrieve a closed account, only the parent or a super admin account should be used. In any case the request to Accounts getAccout or updateAccount should be done using an account which is 1) active 2) has proper permissions to read/update 3) pass the rules of parent/childs(or superadmin)

[...]

@otsakir I can only see an issue when an account had many child accounts and in that case lets make sure that 1)the timeout will be proportional of the number of account we need to remove 2) other threads doesn’t block and only the one jersey thread blocks

**Comment by otsakir** [comment]
Reopening since provided-DID release is not merged yet.
