### ISSUE TITLE
Add password recovery option

### ISSUE THREAD

**Issue by maria-farooq** [RestComm/Restcomm-Connect#1346]
In some scenarios user forgets its account password:
password recovery option can empower them to set a new password.

**Comment by deruelle** [comment]
We now have a password recovery option for cloud at https://accounts.restcomm.com/resetPassword.jsp.

@otsakir It would be good if we could add a Forgot Password ? link to AdminUI and make it configurable via web.xml initparameter and a restcomm.conf or advanced.conf startup script option so cloud users can reset their password. If not provided the Forgot Password ? will not appear.

**Comment by deruelle** [comment]
@otsakir you got it right. 

on web.xml, I thought this could be read from a jsp file, but that may not work for plain html pages.

Yes let's prioritize it as it becomes a recurring issue from people on cloud that don't know how to reset their password.

**Comment by otsakir** [comment]
@deruelle, i'm also wondering if there will also be other small pieces of data in the future that we want Dashboard to know of but which do not consist REST API. 

Also, thinking out loud here..

Does it make sense instead of having our script populate web.xml, create a static file like bootstrap.json under Dashboard which will contain configuration options like this. We'll have to deploy Dashboard as a directory (instead of .war file) in that case so that the file is accessible.

**Comment by otsakir** [comment]
The _second_ half of the issue is solved. `resetPasswordUrl` can now be configured from web.xml. A separate .jsp page produces a json block that contains it. The login page controller retrieves the information from there and if available shows the link. I used an extracted .war file to test. The concept works.

The _first_ half is about adding a configuration script that will extract the url from restcomm.conf and put it in web.xml. The question is how can this be done in AdminUI web application since it's deployed as a .war file.

@jaimecasero , @gvagenas , any pointers here ? What are the best practices for that?

**Comment by jaimecasero** [comment]
im not sure having a script modify the web.xml is under any best practice, since its based on so many non-standard assumptions (exploded deployment available in server....).

Again, if this is env configuration, best practice is to use the environment to provide the configuration. Web.xml is not designed to provide env conf. For that you can use a property file (regular practice, but not best practice IMO), database (again regular practice, and if your app is already using a database is has its advantages), JNDI (not that regular, but at least is reusing EE facilities and you can leverage env-entry in the descriptor).

Apache has a lib that abstracts all the possible configuration sources i mentioend https://commons.apache.org/proper/commons-configuration/

How is the AdminUI currently configured in terms of env cofiguration? Is this the first parameter that needs to be provided from the environment?

including this SO as context on my point 
http://stackoverflow.com/questions/2434888/best-practices-for-defining-and-initializing-variables-in-web-xml-and-then-acces


we may elaborate on standard EE approach with http://www.oracle.com/webfolder/technetwork/tutorials/obe/java/env_entry/env_entry.html

**Comment by otsakir** [comment]
After discussing with @gvagenas and since restcomm configuration is under major review it makes no sense to rely on that mechanism for yet another configuration setting. Thus, the agreed implementation goes like this:

* Deploy AdminUI in exploded form.
* Introduce a new .json file inside AdminUI (e.g. conf/...json with the required setting. An angular service will load this setting from the file and put it inside the login view (implemented).
* For docker installations let docker scripts initialize this value
* For binary installations the administrator should handle editing the .json file himself.

**Comment by otsakir** [comment]
issue is fixed.
