### ISSUE TITLE
Restcomm Client password not updated when admin UI password is updated the first time

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/Restcomm-Connect#1467]
From @deruelle:

I think the rationale should be that if the Account password is updated while in uninitialized state the default password for the Restcomm client bearing the same username should be updated as well

**Comment by ammendonca** [comment]
Closing as fixed, since this is already happening here:
https://github.com/RestComm/Restcomm-Connect/blob/5f5d9484a62627f467b510959cbc94770e476821/restcomm/restcomm.http/src/main/java/org/restcomm/connect/http/AccountsEndpoint.java#L567-L591

Still, it's worth to understand if we want to do this in all of the account password updates (as it is happening currently, even if the default client password has been manually changed) or just when coming from UNINITIALIZED state. WDYT @gvagenas ?
