### ISSUE TITLE
UserAgentManager should remove registration on the first 480 Request timeout and not wait

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#1581]
Currently, UserAgentManager when receives 408 Request Timeout doesn't remove the registration unless last registration update is greater than (pingInterval * 1000 * 3) which could be 3 minutes after the first 408 Request Timeout (given that interval = 60)

This is long time and calls can fail because of that.

My opinion is that we should remove the registration straight away and schedule the call clean up for later. 

This way we avoid failures because Restcomm things the client is registered.

**Comment by deruelle** [comment]
@gvagenas The issue is even if we do that the failures can still happen as we may not have received the timeout but the client may have dropped because of connectivity issues. Also we implemented that behavior to avoid being to aggressive if some clients drops but are able to reconnect almost right away.

Shouldn't we send back an error response saying user not connected instead ?

**Comment by gvagenas** [comment]
closed by #1923
