### ISSUE TITLE
Make Application Log a rolling file to avoid taking too much space

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#1636]
Right now if application log is enabled, it can take a big and evergrowing amount of space. We need a way to make it rolling or limit it somehow.

**Comment by gvagenas** [comment]
@deruelle log4j rolling file appender would do the work, right?

**Comment by deruelle** [comment]
yes I think so.

**Comment by otsakir** [comment]
@gvagenas RVD already uses log4j for system type logging. Can you describe a little how this would work? 

As far as i understand it may be like this:
1. Current application log will be removed (it appends to a log file inside the directory)
2. A separate file say rvd.log under RVD web app will be used. It should accessible from the RVD application so that the user can access his log from the UI.
3. Application identifiers should be logged in each message so that an application can only see its own messages.
4. Export-to-zip will extract the log lines that refer to this application from the main log file and pack them in the exported file.

I'm also not sure whether the needed level of customization will be possible since logging is centrally configured from standalone-sip.xml of jboss.

**Comment by gvagenas** [comment]
@otsakir check log4j appenders and more specific RollingFileAppender https://logging.apache.org/log4j/2.x/manual/appenders.html#RollingFileAppender

**Comment by gvagenas** [comment]
Also at the central log setting we should configure a specific logger for RVD, since you need specific functions for RVD.

**Comment by otsakir** [comment]
After further discussion it seems that the use of a rolling appender is not possible for RVD application logging. The main problem is that application logging is mostly used by users of individual applications that are only interested in their own messages. This means that some sort of filtering should be done from the main application log file to pick only the messages that refer to a specific application. If the number of applications becomes grows, filtering will not be possible in such amounts of data. 

At the same time it's not possible to have a fixed set of log4j appenders that will write to a variable set of output log files per application. It might make some sense to implement a custom log4j appender to offer this capability but RVD use the central Jboss logging system which cannot be easily extended.

Thus, application logging has to be dealt with at the RVD level using a more custom approach. If the _rolling_ part is not possible at least have a way to limit the size of the application log file.

**Comment by otsakir** [comment]
Application logging has been configured to create 4 log files about 300KB each. The naming convention used will produce files like: rvdapp.log, rvdapp-1.log, rvdapp-2.log etc.

Closing the issue as of  c5fedd9
