### ISSUE TITLE
When using the Usage API the uri field in response contains /todo.jsp

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#1689]
See 

True for both Daily and Monthly

curl --user 'ACXXX:YYYYY' 'https://cloud.restcomm.com/restcomm/2012-04-24/Accounts/ACXXXX/Usage/Records/Monthly.json?EndDate=2016-12-31&StartDate=2016-12-01&Category=CALLS'
[
  {
    "category": "calls",
    "description": "Total Calls",
    "account_sid": "ACXXX",
    "start_date": "2016-12-02",
    "end_date": "2016-12-31",
    "usage": "12402",
    "usage_unit": "minutes",
    "count": "638",
    "count_unit": "calls",
    "price": "0",
    "price_unit": "USD",
    "uri": "/todo.json"
  }

**Comment by abdulazizali77** [comment]
Hello, had a quick look, seems to be from here 
/restcomm/restcomm.application/src/main/webapp/WEB-INF/sql/usage.xml
potentially have to modify the uri in getUsageCalls after the SELECT, or pass the uri in then fetch it out again :D 
I reckon #1690 is due to the mybatis functions, might have to test the CONVERT(MIN())
I dont mind taking these two issues up!

**Comment by deruelle** [comment]
@abdulazizali77 sounds great, please by all means do take those issues !
Can you accept the invitation at https://github.com/RestComm/Restcomm-Connect/invitations and sign the Contributor License Agreement at https://telestax.com/open-source/#Contribute to I can assign those issues to you ?

**Comment by abdulazizali77** [comment]
Done! Ill followup with PRs by the end of the week! (hopefully)

**Comment by deruelle** [comment]
@abdulazizali77 awesome. Assigned to you !
