### ISSUE TITLE
Outbound call to conference not completed

### ISSUE THREAD

**Issue by ghjansen** [RestComm/Restcomm-Connect#1942]
Caller that dials to RCML creating the conference is not able to hear the wait song. Caller that dials to the RCML that joins the conference is connected but has no audio.

**Comment by maria-farooq** [comment]
@ghjansen @deruelle  I found the problem: see here
`https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.telephony/src/main/java/org/restcomm/connect/telephony/Conference.java#L211`

- Conference expects `MediaServerConferenceControllerStateChanged` to be sent by MSController but MSController sends `MediaServerControllerStateChanged` 
- `MediaServerControllerStateChanged` <|— `MediaServerConferenceControllerStateChanged` 
- since child is NOT parent so Conference in reality does not process
- `MediaServerControllerStateChanged` sent by `JSR309ConferenceController`
- hence it does not move from initialising state to any other state

After I applied the patch and tested on @ghjansen 's instance:

- Now we are getting proper state changes in conference but MS Controller is actually broadcasting FAILED state
- Please note my patch will only help with issue where conference was not handling in coming MSController state change messages.
- Next thing to do is to synch with dialogic team share why we are getting this error
```
06:28:21,355 DEBUG [com.vendor.dialogic.javax.media.mscontrol.mixer.DlgcXConferenceControlLeg] (MSS-Executor-Thread-1) ControlLegConnectionListener received event = NETWORK_STREAM_FAILURE
06:28:21,355 DEBUG [com.vendor.dialogic.javax.media.mscontrol.sip.DlgcSipB2BUA] (Restcomm-SIP-Servlets-UDPMessageChannelThread-11) Returning from  DlgcSipB2BUA:processSipResponseDoAction
06:28:21,355 DEBUG [com.vendor.dialogic.javax.media.mscontrol.mixer.DlgcXConferenceControlLeg] (MSS-Executor-Thread-1) DlgcXConferenceControlLeg: ControlLegConnectionListener onEvent() connection fail with XMS Error: Fail to establish SIP Session...SIP error: 486
```
on restcomm side we get this
```06:28:21,357 INFO  [org.restcomm.connect.mscontrol.jsr309.Jsr309ConferenceController] (RestComm-akka.actor.default-dispatcher-19) ********** Conference Controller Processing Event: "AllocationEventListener - Mixer" (type = IRRECOVERABLE_FAILURE)
```

I think we can close this ticket as well bcz conference is now moving properly to completed state after we receive failure from XMS.

**Comment by maria-farooq** [comment]
[pushed commit directly to master](https://github.com/RestComm/Restcomm-Connect/commit/aa501591abba5d91094b954e7874aca44de761b1)

**Comment by ghjansen** [comment]
Thank you very much @maria-farooq , after merging your patch into my branch, the conference went back to normal. 😃
