### ISSUE TITLE
Calls not removed from memory even after completing

### ISSUE THREAD

**Issue by maria-farooq** [RestComm/Restcomm-Connect#2313]
**Problem**
we recently found that RC was pilling up `Call` and `MMSCallController` actors in memory. we could see that `Call` was in `stopping` state and `MMSCallController` was in `inactive` state.

**Root Cause**
- Calls were related to `Recording` here is what happens to them:
- RC received `BYE`.
- `Call` goes to `Stopping` state.
- `Call` send msg to `MMSCallController` to clean MediaServer resources.
- `MMSCallController` clean MS resources and give back proper response (`INACTIVE`).
- `Call` moved to `Completed` state & DB was updated properly.
- At `VoiceInterpreter`, RCML kicks in and sends `Hangup` to the call (please mind call was already completed)
- upon receiving `Hangup`, `Call` moves from `Completed` to `Stopping` state **AGAIN**
- and send msg to `MMSCallController` to clean MediaServer resources  **AGAIN**. (please mind `MMSCallController`was already `INACTIVE`)
- `MMSCallController` has not defined action for this situation hence does nothing
- `Call` keeps waiting for response from `MMSCallController` hence actor stays in memory forever.

**Comments & Questions**
- If a `Call` is already `Completed` and we get a `Hangup`, should not we ignore it..
- should a transition from `Completed` to `Stopping` state be allowed? wHy?

**Reference:**
- [ZD](https://telestax.zendesk.com/agent/tickets/34464)
- [code ref 1](https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.telephony/src/main/java/org/restcomm/connect/telephony/Call.java#L2207)
- [code ref 2](https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.telephony/src/main/java/org/restcomm/connect/telephony/Call.java#L2219)

**Comment by gvagenas** [comment]
When Call actor will receive BYE, will from Stopping to Complete state (after receive MmsCallController response) and will notify VoiceInterpreter for the new state.
When VoiceInterpreter receive the Completed state change, will:
1. Ask Call actor to stop media group
2. Will move to `finishRecording`

1. Call actor will receive `StopMediaGroup` but will do nothing since the state is NOT `if (is(inProgress) || is(waitingForAnswer)) {`
2. VI state `finishRecording` will wrapup the recording and will either stop the interpreter or get next verb.

There is a race condition at step `2` where VI might never proceed to the next step and hang there forever and that seems to be the issue here

**Comment by gvagenas** [comment]
When the race condition described at previous comment doesn't occur, VI gets End RCML tag and sends Hangup on the call as @maria-farooq describes in her comment
So actually 2 issues here
