### ISSUE TITLE
Optimize application retrival API wrt Numbers

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#2517]
Being able to produce application-centric listings that also include Incoming Number information is not easily  done. One can retrieve application IDs when retrieving Numbers but when retrieving applications the bound Number SID is not part of the response. Even retrieving a number-by-application-id is not possible.

Here are some solutions i can think of:

1. Include 'Number SID' in the Application API response. It will add a little complexity in the data layer and require a join between IncomingPhoneNumbers and Applications at DB layer. 
2. Improve IncomingPhoneNumbers API search capabilities by being able to return numbers for a specific set of applications SIDs. So the request will contain an array of Applications SIDs and only the numbers that are bound to these apps will be returned. The downside here seems to be that we can't use a GET method to send an array in the body. So, we either switch the method to POST and break our REST semantics or we pass the data in the GET query and have size limitations. 

These are just some thoughts. We probably need a design document here and some thining from the  core team.

**Comment by gvagenas** [comment]
Orestis,

There is one-to-many relationship between Applications and Numbers.
So the 1st option will not work since there might be several Numbers that use the same Application and thus we cannot have `Number SID` in the Application API response. Instead we could have `Number SIDs` {plural}

Related to your option (2), since you need to be able to produce an `application-centric listing` as you mention, a proper solution would be to have Application API to make a join between the Application and Numbers to get the list of Numbers that use the application so your list would be:
```
Application SidA - Number SidA
Application SidA - Number SidB
Application SidA - Number SidC
Application SidA - Number SidD
```
Wouldn't that work?

**Comment by otsakir** [comment]
@gvagenas , i think what you suggest would work great. I can create a design document for core team to review and let you know. 

Is this ok with you ?

**Comment by gvagenas** [comment]
Sure go ahead @otsakir
