### ISSUE TITLE
Olympus-Web takes long time to establish calls

### ISSUE THREAD

**Issue by suyashbhatt** [RestComm/Restcomm-Connect#2798]
Calling a restcomm client from olympus-web takes roughly about 45 seconds. But calling olympus-web client from olympus-android is fast, almost instantaneous.

**Comment by suyashbhatt** [comment]
Chrome console logs: https://gist.github.com/suyashbhatt/d39ef91006bb86274bb5561284834c15

**Comment by ammendonca** [comment]
Hi @suyashbhatt,

First of all, thanks for reporting this! Second, you can report Olympus Web specific issues in https://github.com/restcomm/olympus

This seems like a known issue, it happens when there are network interfaces which have an IP address but have no internet connectivity, so the ICE candidate gathering takes more time, as it waits for that interface to timeout. This typically occurs with VM network adapters (probably that 10.0.0.90 interface?)

The proper solution would be to implement trickle ICE so that it starts using the candidates as they are gathered instead of waiting for the whole thing to complete.

**Comment by suyashbhatt** [comment]
Hi @ammendonca, thanks for your reply. 10.0.0.90 is my device's ip address. I have tried several other devices too and same issue. I will post same question in restcomm/olympus to get support on this issue.
