### ISSUE TITLE
Dashboard call analytics - orange minutes line and right axis make no sense

### ISSUE THREAD

**Issue by ivelin** [RestComm/Restcomm-Connect#309]
1. The minutes are always 0 even though the call count varies
2. The minutes axis has negative numbers which makes no sense for counting minutes.

![screen shot 2015-06-23 at 12 53 43 am](https://cloud.githubusercontent.com/assets/2234901/8299837/697fc2fc-1943-11e5-8983-5f0cba073bf4.png)

**Comment by brainslog** [comment]
This seems to be an issue with the Usage Endpoint calculating the total duration and not so much with the chart itself (except for the negative, that should not be part of it).. it's supposed to present the correct values for minutes.

**Comment by deruelle** [comment]
@brainslog @otsakir @croufay any chance we can fix that one soon ?

**Comment by brainslog** [comment]
Is this still happening ? I think last time I've checked it was working properly, will validate again.

**Comment by deruelle** [comment]
Yes. Thanks @brainslog

**Comment by brainslog** [comment]
After investigation, I figured this issue occurs due to MySQL/MariaDB not allowing to use double-quotes (`"`) for the table fields, as we do @ https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.dao/src/main/java/org/mobicents/servlet/restcomm/dao/mybatis/MybatisUsageDao.java#L160 for duration.

It seems there's no common way for HSQLDB (only accepts `"`) and MariaDB (accepts ` ` `
 and accepts not using anything)

There is the option to use `SET SQL_MODE=ANSI_QUOTES;` on MariaDB script to make it support using double quotes, but this might cause other issues (I think only difference is that literal strings would have to be between single-quotes `'`, anything inside double-quotes would be considered an identifier)

Thoughts ? Meanwhile, I will try to adapt the query so that we can move this part to the engine specific `usage.xml`
