### ISSUE TITLE
Create flow-control/router element in RVD

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#317]
A new  _control_ element for RVD that will be able to execute simple logic.

It may look like this:

![rvd_control_element](https://cloud.githubusercontent.com/assets/8972800/22244444/4dedc258-e234-11e6-9c09-c065f613cb3e.jpg)

It will consist of two parts: A _Condition_  and an _Action_. If the condition evaluates to true the action will be executed.

### Conditions

The condition will have an _operation_ like 'equals', 'greater than', 'isTrue' etc and two operands _left_ and _right_. Both operands will be typical string RVD expressions supporting $core_ syntax. Care should be taken with numeric of boolean stuff. Finally, a set of hierarchical conditions can be supported in the future.

### Actions

The action will be executed if the condition evaluates to true. Most importantly the 'Continue To' action will allow changing the application flow to a specified module. In addition to that an 'Assign' action seems convenient. It will accept two operands and will transfer values from the left to the right. Several actions can be specified. Only a single 'ContinueTo' action is allowed per element and it should be last. Also, action order makes a difference. Re-ordering will be possible.

#### Improvements

It might make sense to 'compile' the control elements to javascript and store it that way. I think it will help in terms of performance.

**Comment by croufay** [comment]
@otsakir, 

This will simplify a lot of things and it is a great step in the right direction.


Thanks

**Comment by FerUy** [comment]
+1 @croufay, great @otsakir. Can't wait to have this in place :)

**Comment by ivelin** [comment]
This will be awesome @otsakir  . Seems like a small incremental level of complexity to RVD UX that is well protected from random code bomb injection and has the potential to substantially increase the use cases that can be covered with RVD.

To add color, I have been spending time lately observing newbies work with Restcomm - from business users to Java developers. EVERYBODY is trying to stay away from writing code. If they can do something with RVD they'd rather do it that way instead of figuring out where to host their app, URL parameters, markup syntax and so on. Its not that they can't do it. Especially the developers. Its just hassle they'd rather avoid.

**Comment by FerUy** [comment]
+1 @ivelin. Excited that it's programmed for 8.1.0 milestone which is turning out to be a monumental one, including many must have features like this one by @otsakir.

**Comment by deruelle** [comment]
@FerUy I think it will be part of 8.2.0 instead as 8.1.0 is planned for early next week and I don't think we have enough time to get it in.

**Comment by FerUy** [comment]
OK @deruelle, anyway it will be great when released 👍

**Comment by otsakir** [comment]
issue fixed
