### ISSUE TITLE
Redirect HTTP to HTTPS when using secure by default.

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#628]
Modify RestComm Docker Image to redirect from HTTP to HTTPS automatically

**Comment by leftyb** [comment]
https://access.redhat.com/solutions/499663

**Comment by otsakir** [comment]
Guys, my 2 cents on the http -> https redirection matter.

Judging by the nature of the request and the service, it seems there are two cases:

1. When requesting static web resources like index.html of UIs it seems good to support redirection. Further requests made from the single page application and calls to REST apis will already switch to https since the context of index.html will be used.

2. When directly reaching out to REST apis that only support https, redirection does not seem the best practice. It didn't fit well in my mind and most comments i found suggested a 403 response should be returned instead of redirection.
