### ISSUE TITLE
Investigate porting RVD workspace to S3

### ISSUE THREAD

**Issue by otsakir** [RestComm/Restcomm-Connect#870]
Investigate whether porting RVD workspace or Amazon S3 is possible with no major refactoring.

**Comment by otsakir** [comment]
Since RVD uses a separate file for each step (ie. verb) there are a lot of requests involved when working with a project. 

Example:

For module *start* that contains 3 Say elements the following files will be created in the *data* directory:
  - start.node
  - start.step1
  - start.step2
  - start.step3

That will result in 4 request to S3 for retrieving each individual file.

Apart form the porting-to-S3 issue, there is no reason to keep information regarding a single module into different files. Merging all this information in a single module file will drastically reduce  I/O operations and thus, requests made to S3.

**Comment by otsakir** [comment]
The patch suggested will require project upgrade in order to merge different step files into a single module file.

It's risky to apply it on top of existing project migration patches related to Project-to-Application transition (performed by @ghjansen) which also affect workspace. There will also be additional friction in merging.

I suggest to do that in two steps. Project-to-Application merging is done first. Port to S3 comes second.

@deruelle, @ghjansen thoughts ?

**Comment by deruelle** [comment]
Agreed.

**Comment by ghjansen** [comment]
I think we could take advantage of the current migration algorithm to execute such task, but considering the different nature of each task, i agree to separate the efforts in two different fronts: one for Project-to-Application and another one specific to S3.

Otherwise we'll expose the algorithm to risky levels of complexity, as described by @otsakir , and increase the chances to face unexpected scenarios.

**Comment by otsakir** [comment]
This issue was moved to RestComm/visual-designer#53
